name: Stats
version: '${project.version}'
main: com.stats.Stats
api-version: 1.18
authors: [ behappy ]
description: 마인크래프트 스텟 플러그인
commands:
  stats:
    description: stats 커멘드
    commands:
      info:
        discription: 스텟 정보 출력
      add:
        discription: 더하기
  alltime:
    description: 역대 접속자